plugins {
    id 'java'
    id 'application'
}

group = 'dev.meshforge'
version = '0.1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'dev.meshforge.Main'
}

dependencies {
    testImplementation('org.junit.jupiter:junit-jupiter:6.0.0')
}

tasks.named('test') {
    useJUnitPlatform()
}